create_clock -name clock -period 20.000 [get_ports {clock}]
create_clock -name clock_delay -period 40.000 [get_pins {clock_delay|q}]
create_clock -name dct_clock -period 40.000 [get_pins {dct_clock|q}]
create_clock -name clock_delay_2 -period 200.000 [get_pins {clock_delay_2|q}]
create_clock -name sck -period 200.000 [get_ports {sck|q}]